services:
  - type: web
    name: pgadmin
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: PGADMIN_DEFAULT_EMAIL
        value: admin@localhost.com
      - key: PGADMIN_DEFAULT_PASSWORD
        value: admin123
